# Generated by Django 5.2.6 on 2025-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash on Pickup"),
                    ("upi", "UPI Payment"),
                    ("card", "Card Payment"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="room_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="special_instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
